FROM bwawrik/bioinformatics

#ENV PATH /opt/local/software/biopieces/bp_bin:$PATH 

ENV BP_DIR /opt/local/software/biopieces
ENV BP_DATA /opt/local/software/biopieces/BP_DATA
ENV BP_TMP /tmp
ENV BP_LOG /opt/local/software/biopieces/BP_LOG

ENV BP_BIN /opt/local/software/biopieces/bp_bin
ENV BP_PERL /opt/local/software/biopieces/code_perl
ENV BP_C /opt/local/software/biopieces/code_c
ENV BP_PYTHON /opt/local/software/biopieces/code_python
ENV BP_RUBY /opt/local/software/biopieces/code_ruby
ENV BP_WWW /opt/local/software/biopieces/www

ENV PATH $PATH:$BP_BIN
ENV PATH $PATH:/opt/local/software/HomerTools/bin
ENV PERL5LIB $PERL5LIB:$BP_PERL
ENV RUBYLIB $RUBYLIB:$BP_RUBY/lib


